import hre from "hardhat";

import { expect } from "chai";
import { loadFixture, time } from "@nomicfoundation/hardhat-network-helpers";

describe("Crowdfunding", () => {

    const GOAL = 1000n;
    const DURATION = 60 * 60;

    async function deployHourCrowdfunding() {
        const [me] = await hre.ethers.getSigners()
        const simpleAuctionContractFactory = await hre.ethers.getContractFactory("Crowdfunding")
        let contractInstance = await simpleAuctionContractFactory.deploy(GOAL, DURATION)
        const startTimestamp = (await contractInstance.deploymentTransaction()?.getBlock())?.timestamp!
        return { contractInstance, startTimestamp }
    }

    it("Should be deployed successfully",
        async function () {
            await loadFixture(deployHourCrowdfunding);
        });

    describe("Deployment", () => {
        it("Should set deadline",
            async function () {
                const { contractInstance, startTimestamp } = await loadFixture(deployHourCrowdfunding);
                expect(await contractInstance.deadline()).to.equal(startTimestamp + DURATION);
            });

        it("Should have set a goal",
            async function () {
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);
                expect(await contractInstance.goal()).to.equal(GOAL);
            });

        it("Should have an owner",
            async function () {
                const [me] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);
                expect(await contractInstance.owner()).to.equal(me.address);
            });
    });

    describe("Contributions", () => {
        it("Should accept contributions",
            /*
Generated by Mistral AI Chat Balanced 22.04.2026
Modified
            */
            async function () {
                const [_me, other] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);
                const contributionAmount = 100;

                await expect(contractInstance.connect(other).contribute({ value: contributionAmount }))
                    .to.emit(contractInstance, "Contributed")
                    .withArgs(other.address, contributionAmount);
                expect(await contractInstance.contributions(other.address)).to.equal(contributionAmount);
                expect(await contractInstance.totalRaised()).to.equal(contributionAmount);
            });
    });

    describe("Refunds", () => {
        it("Should allow refunding if the goal was not reached",
            async function () {
                const [_me, other] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);
                const contributionAmount = 100;

                await contractInstance.connect(other).contribute({ value: contributionAmount });
                await time.increase(DURATION + 1);
                await expect(contractInstance.connect(other).refund())
                    .to.emit(contractInstance, "Refunded")
                    .withArgs(other.address, contributionAmount);
                expect(await contractInstance.contributions(other.address)).to.equal(0);
            });
    });

    describe("Withdrawals", () => {
        it("Should allow the owner to withdraw when the goal is reached",
            async function () {
                const [me, other] = await hre.ethers.getSigners()

                const { contractInstance } = await loadFixture(deployHourCrowdfunding);

                await contractInstance.connect(other).contribute({ value: GOAL });
                await time.increase(DURATION + 1);

                const initialBalance = await hre.ethers.provider.getBalance(me.address);
                const tx = await contractInstance.connect(me).withdraw();
                const receipt = (await tx.wait())!;
                const gasCost = receipt.gasUsed * receipt.gasPrice;
                const finalBalance = await hre.ethers.provider.getBalance(me.address);

                expect(finalBalance + gasCost).to.be.at.equal(initialBalance + GOAL);
            });
    });

    describe("Errors", () => {
        it("Should revert if contributing after deadline",
            async function () {
                const [_me, other] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);

                await time.increase(DURATION + 1);
                await expect(contractInstance.connect(other).contribute({ value: 100 }))
                    .to.be.revertedWith("Deadline passed");
            });

        it("Should revert if withdrawing before deadline",
            async function () {
                const [me] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);

                await expect(contractInstance.connect(me).withdraw())
                    .to.be.revertedWith("Deadline not reached");
            });

        it("Should revert if refunding before deadline",
            async function () {
                const [_me, other] = await hre.ethers.getSigners()
                const { contractInstance } = await loadFixture(deployHourCrowdfunding);

                await contractInstance.connect(other).contribute({ value: 100 });
                await expect(contractInstance.connect(other).refund())
                    .to.be.revertedWith("Deadline not reached");
            });
    });
});