import hre from "hardhat";

import { expect } from "chai";
import { loadFixture, time } from "@nomicfoundation/hardhat-network-helpers";


describe("SimpleOpenAuction", () => {
    const AUCTION_TIME = 60 * 60; // one hour

    async function deployHourAuction() {
        const [me] = await hre.ethers.getSigners()
        const simpleAuctionContractFactory = await hre.ethers.getContractFactory("SimpleAuction")
        let contractInstance = await simpleAuctionContractFactory.deploy(AUCTION_TIME, me.address)
        const auctionsStartTimestamp = (await contractInstance.deploymentTransaction()?.getBlock())?.timestamp!
        return { contractInstance, auctionsStartTimestamp }
    }

    it(
        "Should be deployed successfully",
        async function () {
            await loadFixture(deployHourAuction)
        })

    describe("Deployment", () => {
        it("Should set the auction end time",
            async function () {
                const { contractInstance, auctionsStartTimestamp } = await loadFixture(deployHourAuction)
                expect(await contractInstance.auctionEndTime()).to.equal(auctionsStartTimestamp + AUCTION_TIME)
            })

        it("Should set the beneficiary",
            async function () {
                const { contractInstance } = await loadFixture(deployHourAuction)
                const [me] = await hre.ethers.getSigners()
                expect(me.address).to.equal(await contractInstance.beneficiary())
            })
    })

    /*
Generated by Anthropic Claude Sonnet 4.6 Adaptive 22.04.2026
    */
    describe("Execution", () => {
        it(
            "Should update highest bidder",
            async function () {
                const [_me, bidder1, bidder2] = await hre.ethers.getSigners();
                const { contractInstance } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") })
                expect(await contractInstance.highestBidder()).to.equal(bidder1.address)
                expect(await contractInstance.highestBid()).to.equal(hre.ethers.parseEther("1.0"))

                await contractInstance.connect(bidder2).bid({ value: hre.ethers.parseEther("2.0") })
                expect(await contractInstance.highestBidder()).to.equal(bidder2.address)
                expect(await contractInstance.highestBid()).to.equal(hre.ethers.parseEther("2.0"))
            })

        it(
            "Should allow withdrawing funds",
            async function () {
                const [_me, bidder1, bidder2] = await hre.ethers.getSigners();
                const { contractInstance } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") })
                await contractInstance.connect(bidder2).bid({ value: hre.ethers.parseEther("2.0") })

                // bidder1 was outbid and should be able to withdraw their 1 ETH
                const balanceBefore = await hre.ethers.provider.getBalance(bidder1.address)
                const tx = await contractInstance.connect(bidder1).withdraw()
                const receipt = await tx.wait()
                const gasUsed = receipt!.gasUsed * receipt!.gasPrice
                const balanceAfter = await hre.ethers.provider.getBalance(bidder1.address)

                expect(balanceAfter).to.equal(balanceBefore + hre.ethers.parseEther("1.0") - gasUsed)
            })

        it(
            "Should pay to the beneficiary after the auction has ended",
            async function () {
                const [me, bidder1] = await hre.ethers.getSigners();
                const { contractInstance, auctionsStartTimestamp } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") })

                await time.increaseTo(auctionsStartTimestamp + AUCTION_TIME + 1)

                const beneficiaryBalanceBefore = await hre.ethers.provider.getBalance(me.address)
                const endTx = await contractInstance.connect(bidder1).auctionEnd()
                const endReceipt = await endTx.wait()

                const beneficiaryBalanceAfter = await hre.ethers.provider.getBalance(me.address)
                expect(beneficiaryBalanceAfter).to.equal(beneficiaryBalanceBefore + hre.ethers.parseEther("1.0"))
            })
    })

    describe("Events", () => {
        it(
            "Should emit HighestBidIncreased when a new highest bid is placed",
            async function () {
                const [_me, bidder1] = await hre.ethers.getSigners();
                const { contractInstance } = await loadFixture(deployHourAuction)

                await expect(contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") }))
                    .to.emit(contractInstance, "HighestBidIncreased")
                    .withArgs(bidder1.address, hre.ethers.parseEther("1.0"))
            })

        it(
            "Should emit AuctionEnded with the winner and final bid amount",
            async function () {
                const [_me, bidder1] = await hre.ethers.getSigners();
                const { contractInstance, auctionsStartTimestamp } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") })
                await time.increaseTo(auctionsStartTimestamp + AUCTION_TIME + 1)

                await expect(contractInstance.auctionEnd())
                    .to.emit(contractInstance, "AuctionEnded")
                    .withArgs(bidder1.address, hre.ethers.parseEther("1.0"))
            })
    })

    describe("Errors", () => {
        it(
            "Should revert with AuctionAlreadyEnded when bidding after the auction has ended",
            async function () {
                const [_me, bidder1] = await hre.ethers.getSigners();
                const { contractInstance, auctionsStartTimestamp } = await loadFixture(deployHourAuction)

                await time.increaseTo(auctionsStartTimestamp + AUCTION_TIME + 1)

                await expect(contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") }))
                    .to.be.revertedWithCustomError(contractInstance, "AuctionAlreadyEnded")
            })

        it(
            "Should revert with BidNotHighEnough when bid does not exceed the current highest bid",
            async function () {
                const [_me, bidder1, bidder2] = await hre.ethers.getSigners();
                const { contractInstance } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("2.0") })

                await expect(contractInstance.connect(bidder2).bid({ value: hre.ethers.parseEther("1.0") }))
                    .to.be.revertedWithCustomError(contractInstance, "BidNotHighEnough")
                    .withArgs(hre.ethers.parseEther("2.0"))
            })

        it(
            "Should revert with AuctionNotYetEnded when calling auctionEnd before the auction has ended",
            async function () {
                const { contractInstance } = await loadFixture(deployHourAuction)

                await expect(contractInstance.auctionEnd())
                    .to.be.revertedWithCustomError(contractInstance, "AuctionNotYetEnded")
            })

        it(
            "Should revert with AuctionEndAlreadyCalled when auctionEnd is called more than once",
            async function () {
                const [_me, bidder1] = await hre.ethers.getSigners();
                const { contractInstance, auctionsStartTimestamp } = await loadFixture(deployHourAuction)

                await contractInstance.connect(bidder1).bid({ value: hre.ethers.parseEther("1.0") })
                await time.increaseTo(auctionsStartTimestamp + AUCTION_TIME + 1)

                await contractInstance.auctionEnd()

                await expect(contractInstance.auctionEnd())
                    .to.be.revertedWithCustomError(contractInstance, "AuctionEndAlreadyCalled")
            })
    })
})
